# Generated by Django 5.0.7 on 2024-08-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netconfapp', '0002_alter_backup_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='success',
            field=models.BooleanField(blank=True),
        ),
    ]
