# Generated by Django 5.0.7 on 2024-08-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netconfapp', '0004_alter_backup_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='success',
            field=models.BooleanField(),
        ),
    ]
