# Generated by Django 5.0.7 on 2024-08-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netconfapp', '0006_alter_backup_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='success',
        ),
        migrations.AddField(
            model_name='backup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
