# Generated by Django 5.0.7 on 2024-08-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netconfapp', '0007_remove_backup_success_backup_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='backup',
            unique_together={('device', 'schedule_date', 'schedule_time')},
        ),
        migrations.AddField(
            model_name='backup',
            name='success',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Successful'), ('failed', 'Failed')], default='failed', max_length=10),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='backup',
            name='status',
        ),
    ]
