# Generated by Django 5.0.7 on 2024-08-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netconfapp', '0008_alter_backup_unique_together_backup_success_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='backup',
            unique_together=set(),
        ),
    ]
