# Generated by Django 5.0.7 on 2024-08-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netconfapp', '0009_alter_backup_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backup',
            old_name='success',
            new_name='status',
        ),
    ]
