# Generated by Django 5.0.7 on 2024-08-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netconfapp', '0011_alter_backup_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='configuration',
        ),
    ]
