# Generated by Django 5.0.7 on 2024-08-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netconfapp', '0012_remove_backup_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='configuration',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
